// Generated by gencpp from file ardrone_joy/GoToPoseRequest.msg
// DO NOT EDIT!


#ifndef ARDRONE_JOY_MESSAGE_GOTOPOSEREQUEST_H
#define ARDRONE_JOY_MESSAGE_GOTOPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardrone_joy
{
template <class ContainerAllocator>
struct GoToPoseRequest_
{
  typedef GoToPoseRequest_<ContainerAllocator> Type;

  GoToPoseRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , phi1(0.0)
    , phi2(0.0)
    , phi3(0.0)  {
    }
  GoToPoseRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , phi1(0.0)
    , phi2(0.0)
    , phi3(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _phi1_type;
  _phi1_type phi1;

   typedef double _phi2_type;
  _phi2_type phi2;

   typedef double _phi3_type;
  _phi3_type phi3;





  typedef boost::shared_ptr< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPoseRequest_

typedef ::ardrone_joy::GoToPoseRequest_<std::allocator<void> > GoToPoseRequest;

typedef boost::shared_ptr< ::ardrone_joy::GoToPoseRequest > GoToPoseRequestPtr;
typedef boost::shared_ptr< ::ardrone_joy::GoToPoseRequest const> GoToPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ardrone_joy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ardrone_joy': ['/home/vlad/ardrone_simulator/src/pid_control_ardrone/ardrone_joy/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25bee84ee6ee3ba4b50689a3eecbd1d1";
  }

  static const char* value(const ::ardrone_joy::GoToPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25bee84ee6ee3ba4ULL;
  static const uint64_t static_value2 = 0xb50689a3eecbd1d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardrone_joy/GoToPoseRequest";
  }

  static const char* value(const ::ardrone_joy::GoToPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 phi1\n\
float64 phi2\n\
float64 phi3\n\
";
  }

  static const char* value(const ::ardrone_joy::GoToPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.phi1);
      stream.next(m.phi2);
      stream.next(m.phi3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardrone_joy::GoToPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardrone_joy::GoToPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "phi1: ";
    Printer<double>::stream(s, indent + "  ", v.phi1);
    s << indent << "phi2: ";
    Printer<double>::stream(s, indent + "  ", v.phi2);
    s << indent << "phi3: ";
    Printer<double>::stream(s, indent + "  ", v.phi3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDRONE_JOY_MESSAGE_GOTOPOSEREQUEST_H
