// Generated by gencpp from file ardrone_joy/GoToPoseResponse.msg
// DO NOT EDIT!


#ifndef ARDRONE_JOY_MESSAGE_GOTOPOSERESPONSE_H
#define ARDRONE_JOY_MESSAGE_GOTOPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardrone_joy
{
template <class ContainerAllocator>
struct GoToPoseResponse_
{
  typedef GoToPoseResponse_<ContainerAllocator> Type;

  GoToPoseResponse_()
    : success(false)  {
    }
  GoToPoseResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPoseResponse_

typedef ::ardrone_joy::GoToPoseResponse_<std::allocator<void> > GoToPoseResponse;

typedef boost::shared_ptr< ::ardrone_joy::GoToPoseResponse > GoToPoseResponsePtr;
typedef boost::shared_ptr< ::ardrone_joy::GoToPoseResponse const> GoToPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ardrone_joy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ardrone_joy': ['/home/zhu/ardrone_simulator/src/pid_control_ardrone-master/ardrone_joy/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::ardrone_joy::GoToPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardrone_joy/GoToPoseResponse";
  }

  static const char* value(const ::ardrone_joy::GoToPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
";
  }

  static const char* value(const ::ardrone_joy::GoToPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardrone_joy::GoToPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardrone_joy::GoToPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDRONE_JOY_MESSAGE_GOTOPOSERESPONSE_H
