// Generated by gencpp from file ardrone_joy/GoToPose.msg
// DO NOT EDIT!


#ifndef ARDRONE_JOY_MESSAGE_GOTOPOSE_H
#define ARDRONE_JOY_MESSAGE_GOTOPOSE_H

#include <ros/service_traits.h>


#include <ardrone_joy/GoToPoseRequest.h>
#include <ardrone_joy/GoToPoseResponse.h>


namespace ardrone_joy
{

struct GoToPose
{

typedef GoToPoseRequest Request;
typedef GoToPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToPose
} // namespace ardrone_joy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ardrone_joy::GoToPose > {
  static const char* value()
  {
    return "f8f1e7d035fd434dffbcb388b3e668a1";
  }

  static const char* value(const ::ardrone_joy::GoToPose&) { return value(); }
};

template<>
struct DataType< ::ardrone_joy::GoToPose > {
  static const char* value()
  {
    return "ardrone_joy/GoToPose";
  }

  static const char* value(const ::ardrone_joy::GoToPose&) { return value(); }
};


// service_traits::MD5Sum< ::ardrone_joy::GoToPoseRequest> should match 
// service_traits::MD5Sum< ::ardrone_joy::GoToPose > 
template<>
struct MD5Sum< ::ardrone_joy::GoToPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ardrone_joy::GoToPose >::value();
  }
  static const char* value(const ::ardrone_joy::GoToPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardrone_joy::GoToPoseRequest> should match 
// service_traits::DataType< ::ardrone_joy::GoToPose > 
template<>
struct DataType< ::ardrone_joy::GoToPoseRequest>
{
  static const char* value()
  {
    return DataType< ::ardrone_joy::GoToPose >::value();
  }
  static const char* value(const ::ardrone_joy::GoToPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ardrone_joy::GoToPoseResponse> should match 
// service_traits::MD5Sum< ::ardrone_joy::GoToPose > 
template<>
struct MD5Sum< ::ardrone_joy::GoToPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ardrone_joy::GoToPose >::value();
  }
  static const char* value(const ::ardrone_joy::GoToPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardrone_joy::GoToPoseResponse> should match 
// service_traits::DataType< ::ardrone_joy::GoToPose > 
template<>
struct DataType< ::ardrone_joy::GoToPoseResponse>
{
  static const char* value()
  {
    return DataType< ::ardrone_joy::GoToPose >::value();
  }
  static const char* value(const ::ardrone_joy::GoToPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDRONE_JOY_MESSAGE_GOTOPOSE_H
